### ISSUE TITLE
echo "Hello World!" will give you `dquote>` in Linux

### ISSUE THREAD

**Issue by npalladium** [groda/big_data#1]
## Expected Behavior
Message is echoed.

## Current Behavior
'dquote>` appears on the command line.

## Possible Solution
Bash expands `!` as it is in double quotes. Switch to single quotes. Or drop the '!'.

## Context (Environment)
Ubuntu 16.04.6 LTS with zsh. But behavior will be same on any Bash shell on any other distro.

**Comment by groda** [comment]
Hi thanks very much for pointing that out. With single quotes it should work now.

**Comment by informatik01** [comment]
Other option, **if** still using **double quotes**, is just to _escape_ the exclamation mark: `\!`

### Example:
`> echo "Hello, world\!"`

**Comment by groda** [comment]
Thanks. I included the double quotes option.

**Comment by Aryan873-hub** [comment]
bquote>
